externalSecretKey: petpop/internal

server:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-941c8b8f2460e6177e051e3907fbbaee8b981fd4
  hostname: internal.petpop.fun

backoffice:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-941c8b8f2460e6177e051e3907fbbaee8b981fd4
  hostname: petpop-internal-backoffice.9c.gg

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-941c8b8f2460e6177e051e3907fbbaee8b981fd4
  rankingWorker:
    enabled: true
  blockResetWorker:
    enabled: true
  walletMonitorWorker:
    enabled: false
