apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ragnarok-breaker-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: main
    path: charts/ragnarok-breaker
    helm:
      valueFiles:
        - /9c-main/ragnarok-breaker-production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ragnarok-breaker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
