externalSecretKey: ragnarok-breaker/production

imagePullSecret:
  secretKey: ragnarok-breaker/dockerhub

worker:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e

v8Gateway:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e

yggRedeem:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e
  deployment:
    replicas: 2
  httpRoute:
    enabled: true
    hostnames:
      - ygg-redeem.9c.gg

logStream:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e

yggQuestWorker:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e
  replicas: 2

bqAnalyticsWorker:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e
