externalSecretKey: ragnarok-breaker/production

image:
  repository: planetariumhq/ragnarok-breaker-worker
  tag: git-b3cf4800925e0ebb1dd422c5d46928d2e0934000

imagePullSecret:
  secretKey: ragnarok-breaker/dockerhub

yggGateway:
  enabled: true
  externalSecretKey: ygg-gateway/production
  image:
    tag: git-015c233d8a48c63292e6e565f5ea9639bec8f721
  deployment:
    replicas: 2
  httpRoute:
    enabled: true
    hostnames:
      - ygg-gateway.9c.gg
