externalSecretKey: ragnarok-breaker/staging-web3

imagePullSecret:
  secretKey: ragnarok-breaker/dockerhub

worker:
  image:
    tag: git-ee184bdd7872759d9bd02acddc1982e849cdf4f2

v8Gateway:
  image:
    tag: git-ee184bdd7872759d9bd02acddc1982e849cdf4f2

logStream:
  image:
    tag: git-ee184bdd7872759d9bd02acddc1982e849cdf4f2

yggRedeem:
  image:
    tag: git-ee184bdd7872759d9bd02acddc1982e849cdf4f2
  httpRoute:
    enabled: true
    hostnames:
      - ygg-redeem-staging.9c.gg

yggQuestWorker:
  image:
    tag: git-ee184bdd7872759d9bd02acddc1982e849cdf4f2

bqAnalyticsWorker:
  image:
    tag: git-ee184bdd7872759d9bd02acddc1982e849cdf4f2
