{{- if and .Values.api.enabled .Values.api.hostnames }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dcc-bridge-api
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: web
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    {{- toYaml .Values.api.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dcc-bridge-api
          port: 80
{{- end }}
