{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dcc-bridge-api
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  selector:
    app: dcc-bridge-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
{{- end }}
