{{- if .Values.serviceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
{{- end }}
