apiVersion: apps/v1
kind: Deployment
metadata:
  name: ygg-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: ygg-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ygg-gateway
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: ygg-gateway
  template:
    metadata:
      labels:
        app: ygg-gateway
    spec:
      {{- if .Values.imagePullSecret.secretKey }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
        - name: ygg-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
          env:
            - name: PORT
              value: {{ .Values.deployment.port | quote }}
          envFrom:
            - secretRef:
                name: ygg-gateway-env
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
