{{- if .Values.externalSecretKey }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ygg-gateway-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: ygg-gateway-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secretsmanager
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
{{- end }}
{{- if .Values.imagePullSecret.secretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: {{ .Values.imagePullSecret.name }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"{{ `{{ .registry }}` }}":{"username":"{{ `{{ .username }}` }}","password":"{{ `{{ .password }}` }}","auth":"{{ `{{ printf "%s:%s" .username .password | b64enc }}` }}"}}}
  data:
    - secretKey: registry
      remoteRef:
        key: {{ .Values.imagePullSecret.secretKey }}
        property: registry
    - secretKey: username
      remoteRef:
        key: {{ .Values.imagePullSecret.secretKey }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.imagePullSecret.secretKey }}
        property: password
{{- end }}
