externalSecretKey: ragnarok-breaker/staging

image:
  repository: planetariumhq/ragnarok-breaker-worker
  tag: git-7a923800ef25c942171a2e251a9814cb6d30d841

imagePullSecret:
  secretKey: ragnarok-breaker/dockerhub

yggGateway:
  enabled: true
  image:
    tag: git-1b36f5493f1c9fdd76c618c7ea381bcd91026c4e
  httpRoute:
    enabled: true
    hostnames:
      - ygg-gateway-staging.9c.gg
