externalSecretKey: ragnarok-breaker/staging

imagePullSecret:
  secretKey: ragnarok-breaker/dockerhub

worker:
  image:
    tag: git-088af99e6359ab9062796dd43fca5a43b92335f5

v8Gateway:
  image:
    tag: git-088af99e6359ab9062796dd43fca5a43b92335f5

yggRedeem:
  image:
    tag: git-088af99e6359ab9062796dd43fca5a43b92335f5
  httpRoute:
    enabled: true
    hostnames:
      - ygg-redeem-staging.9c.gg

logStream:
  image:
    tag: git-088af99e6359ab9062796dd43fca5a43b92335f5

yggQuestWorker:
  image:
    tag: git-088af99e6359ab9062796dd43fca5a43b92335f5
