externalSecretKey: petpop/prod

server:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-8e9bd3994a502352efa27e475e0e853a21d6485f
  hostnames:
    - petpop.fun
    - www.petpop.fun
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  nodeSelector:
    node.kubernetes.io/type: general

backoffice:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-8e9bd3994a502352efa27e475e0e853a21d6485f
  hostname: petpop-backoffice.9c.gg
  nodeSelector:
    node.kubernetes.io/type: general

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-8e9bd3994a502352efa27e475e0e853a21d6485f
  nodeSelector:
    node.kubernetes.io/type: general
  rankingWorker:
    enabled: true
  blockResetWorker:
    enabled: true
  walletMonitorWorker:
    enabled: true
