{{- range $.Values.network }}
{{- $name := . }}
{{- $enabled := true }}
{{- if kindIs "map" . }}
  {{- $name = .name }}
  {{- if hasKey . "enabled" }}
    {{- $enabled = .enabled }}
  {{- end }}
{{- end }}
{{- if $enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoURL | default "https://github.com/planetarium/9c-infra.git" }}
    targetRevision: {{ $.Values.targetRevision | default "main" }}
    path: charts/all-in-one
    helm:
      valueFiles:
      - /{{ $.Values.path }}/network/general.yaml
      - /{{ $.Values.path }}/network/{{ $name }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $name }}
---
{{- end }}
{{- end }}
