{{- if .Values.bqAnalyticsWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bq-analytics-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: bq-analytics-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: bq-analytics-worker
spec:
  replicas: {{ .Values.bqAnalyticsWorker.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bq-analytics-worker
  template:
    metadata:
      labels:
        app: bq-analytics-worker
    spec:
      {{- if .Values.imagePullSecret.secretKey }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
        - name: bq-analytics-worker
          image: "{{ .Values.bqAnalyticsWorker.image.repository }}:{{ .Values.bqAnalyticsWorker.image.tag }}"
          imagePullPolicy: {{ .Values.bqAnalyticsWorker.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: ragnarok-breaker-env
          resources:
            {{- toYaml .Values.bqAnalyticsWorker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
{{- end }}
