{{- if .Values.yggGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ygg-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: ygg-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ygg-gateway
spec:
  type: ClusterIP
  selector:
    app: ygg-gateway
  ports:
    - name: http
      port: {{ .Values.yggGateway.service.port }}
      targetPort: {{ .Values.yggGateway.deployment.port }}
      protocol: TCP
{{- end }}
