{{- if and .Values.yggGateway.enabled .Values.yggGateway.externalSecretKey }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ygg-gateway-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: ygg-gateway-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.yggGateway.externalSecretKey }}
{{- end }}
