{{- if .Values.yggRedeem.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ygg-redeem
  namespace: {{ .Release.Namespace }}
  labels:
    app: ygg-redeem
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ygg-redeem
spec:
  type: ClusterIP
  selector:
    app: ygg-redeem
  ports:
    - name: http
      port: {{ .Values.yggRedeem.service.port }}
      targetPort: {{ .Values.yggRedeem.deployment.port }}
      protocol: TCP
{{- end }}
