externalSecretKey: ragnarok-breaker/dev-web3

imagePullSecret:
  secretKey: ragnarok-breaker/dockerhub

worker:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e

v8Gateway:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e

logStream:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e

yggRedeem:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e
  httpRoute:
    enabled: true
    hostnames:
      - ygg-redeem-dev.9c.gg

yggQuestWorker:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e

bqAnalyticsWorker:
  image:
    tag: git-a8daa0f6859e8d4c3f349f0121627a63725bfc6e
