apiVersion: v2
name: ragnarok-breaker
description: Ragnarok Breaker workloads (workers + v8-gateway + log-stream + playfull-worker + anticheat-alert-worker + mail-send-worker + league-reward-worker + analytics-worker)
type: application
version: 0.4.0
appVersion: 0.2.0
